# -*- coding: utf-8 -*-
"""BipedDQN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RaYrA4rg9MyggIYkn5mBRr0kLXQDGfLd
"""

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from collections import namedtuple
from collections import deque
import random
import math

import pybullet as p
import pybullet_data


EPISODES = 3500

EPS = 1.0
EPS_DECAY = 0.995
EPS_MIN = 0.01

GAMMA = 0.8
LEARNING_RATE = 0.01
BATCH_SIZE = 64

TARGET_REWARD = 50 #수정?

TARGET_HEIGHT = 20 #수정필요

M_W = 1
H_W = 0.3
T_W = 0.3
E_W = 0.3


class DQN(nn.Module):
  def __init__(self, state_size, action_size):
    super(DQN,self).__init__()

    self.fc1 = nn.Linear(state_size, 64)
    self.fc2 = nn.Linear(64,64)
    self.fc3 = nn.Linear(64,action_size)

  def forward(self, x):
    x = torch.relu(self.fc1(x))
    x = torch.relu(self.fc2(x))
    x = torch.relu(self.fc3(x))

    return x



class ReplayMemory:
  def __init__(self,capacity):
    self.memory = deque(maxlen=capacity)

    pass

  def push(self,transition):
    self.memory.append(transition)
    pass

  def sample(self,batch_size):
    return random.sample(self.memory, batch_size)

  def __len__(self):
    return len(self.memory)

class Agent(nn.Module,ReplayMemory,DQN):
    def __init__(self,state_size,action_size):
      super(DQN, self).__init__()
      self.state_size = state_size
      self.action_size = action_size

      self.model = DQN(state_size, action_size)
      self.target_model = DQN(state_size, action_size)

      self.target_model.load_state_dict(self.model.state_dict)

      self.optimizer = optim.Adam(self.model.parameters(), lr=LEARNING_RATE)

    def act(self, state):
      '''
      implement epsilon-greedy
      '''
      if np.random.rand() <= EPS:
          return random.randrange(self.action_size)
      state = torch.FloatTensor(state).unsqueeze(0)
      with torch.no_grad():
          q_values = self.model(state)
      return np.argmax(q_values.cpu().numpy())

    def train(self, batch_size):
        if len(self.memory) < batch_size:
            return
        
        minibatch = self.memory.sample(batch_size)

        states = torch.FloatTensor(t[0] for t in minibatch)
        action = torch.FloatTensor(t[1] for t in minibatch)
        reward = torch.FloatTensor(t[2] for t in minibatch)
        next_state = torch.FloatTensor(t[3] for t in minibatch)
        dones = torch.FloatTensor(t[4] for t in minibatch)

        q_values = self.model(states).gather(1,action).squeeze(1)
        next_q_values = self.model(next_state).gather(1, action).max(1)[0]
        targets = reward + (GAMMA * next_q_values * (1 - dones))

        loss = nn.MSELoss()(q_values, targets)
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()

        if EPS > EPS_MIN:
            EPS *= EPS_DECAY


  

class Bot:
  def __init__(self,filename):


    p.connect(p.GUI)
    p.setGravity(0, 0, -9.81)
    p.setAdditionalSearchPath(pybullet_data.getDataPath())
    self.plane = p.loadURDF("plane.urdf")
    self.actor = p.loadURDF(filename, basePosition=[0, 0, 1])

    pass

  def getJointState(self):
    num_joints = p.getNumJoints(self.actor)

    Joints = []
    Joints_raw = []

    # JointState = namedtuple('JointState',['angle', 'velocity'])

    for joint_idx in range(num_joints):
      data = p.getJointState
      Joints_raw.append(data)

      angle = data[0]
      velocity = data[1]
      torque = data[3]

      # Joints.append(JointState(angle=angle,velocity=velocity))

      Joints.append(angle)
      Joints.append(velocity)
      Joints.append(torque)
    
    return Joints, Joints_raw


  def getBodyState(self):

    Body = []
  
    position, orientation = p.getBasePositionAndOrientation(self.actor)



    linear_velocity, angular_velocity = p.getBaseVelocity(self.actor)
    # BodyState = namedtuple('BodyState',['position','angle','linear_velocity','angular_velocity'])

    # Body = BodyState(position=position,angle=orientation,linear_velocity=linear_velocity,angular_velocity=angular_velocity)

    Body.extend(linear_velocity) 
    Body.extend(position)     
    Body.extend(orientation)   
    Body.extend(angular_velocity) 

    return Body #[vx, vy, vz, x, y, z, qx, qy, qz, qw, wx, wy, wz] 
        
  def getReward(self,state,joint_raw):
      '''
      calculate reward due to the state of the actor.
      '''
      moveReward = state[0]


      heightPenalty = abs(state[5] - TARGET_HEIGHT)

      tilt = (p.getEulerFromQuaternion(state[6]), p.getEulerFromQuaternion(state[7]))

      tiltPenalty = abs(tilt[0]) + abs(tilt[1])

      energy_penalty = sum(abs(js[1] * js[3]) for js in joint_raw)
      
      reward = M_W*moveReward - T_W*tiltPenalty - H_W*heightPenalty - E_W*energy_penalty

      return reward
  
  
  def step(self,action:tuple):
     #action으로 받아온 theta 적용하기
     self.setJoint(0,action[0])
     self.setJoint(1,action[1])
     self.setJoint(2,action[2])
     self.setJoint(3,action[3])
     self.setJoint(4,action[4])
     self.setJoint(5,action[5])     
     
     p.stepSimulation()

     bodyState = self.getBodyState()
     jointState, joint_raw = self.getJointState()

     new_state = (*bodyState, *jointState)

     reward = self.getReward(new_state,joint_raw)

     

     return new_state, reward
  
  def setJoint(self,jointIdx,target):
     p.setJointMotorControl2(
     bodyIndex=self.actor,             
     jointIndex=jointIdx,         
     controlMode=p.POSITION_CONTROL,    
     targetPosition=math.radians(target)    
     force=500    
     )     

     pass                 

  

    


state_size = 
action_size = 6

agent = Agent(state_size, action_size)
bot = Bot('...')

for e in range(EPISODES):
    # state = env.reset()

    state = np.reshape(state, [1, state_size])
    total_reward = 0
    done = False

    while not done:
        bodyState = bot.getBodyState()
        jointState, _ = bot.getJointState()
        state = (*bodyState,*jointState)

        action = agent.act(*state)

        #observations required
        #관절 각속도 및 각 - ok
        #몸체 각속도 및 각 - ok
        #접촉력 - 보류
        #이전 action 피드백

        next_state, reward = bot.step(action)
        next_state = np.reshape(next_state, [1, state_size])

        
        reward = bot.getReward(next_state)

        agent.memory.push((state, action, reward, next_state, done))
        state = next_state
        total_reward += reward

        if total_reward >= TARGET_REWARD:
           done = True

        if done:
            agent.update_target_model()
            print(f"Episode: {e+1}/{EPISODES}, Score: {total_reward}")
            break

        agent.train(BATCH_SIZE)